name: Run Interchain Test

on:
  push: 
    branches:
      - spoorthi/interchain-test
  workflow_dispatch:

jobs:
  run-interchaintest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: strangelove-ventures/interchaintest
          ref: v4
      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19
      - name: Build
        run: make interchaintest
        
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: archway
      - name: Run interchain test
        run: ./bin/interchaintest -matrix ./archway/interchaintest_matrix.json
    
