name: Run Interchain Test

on:
  push: 
    branches:
      - spoorthi/interchain-test
  workflow_dispatch:

jobs:
  build-archway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build Archway binary
        run: |
          make build 
          cp ./build/archwayd ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Archway docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: archway:local
          outputs: type=docker,dest=/tmp/archway.tar
        
      - name: Upload the docker image
        uses: actions/upload-artifact@v3
        with:
          name: archway
          path: /tmp/archway.tar
          retention-days: 1
    

  build-interchaintest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: strangelove-ventures/interchaintest

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: make interchaintest
    
      - name: Upload the binary
        uses: actions/upload-artifact@v3
        with:
          name: interchaintest
          path: ./bin/interchaintest
          retention-days: 1

  run-default: 
    name: default
    needs: [build-interchaintest,build-archway]
    uses: ./.github/workflows/interchaintest_runner.yml
    with:
      test-matrix: 'interchaintest_matrix.json'



  cleanup:
    name: Delete artifacts 🗑️
    needs: [run-default]
    runs-on: ubuntu-latest

    steps:
      - name: Delete interchaintest # Delete the binary from workflow artifacts as its not needed anymore
        uses: geekyeggo/delete-artifact@v2
        with:
          name: interchaintest
          failOnError: false
      
      - name: Delete sg # Delete the archway docker image from workflow artifacts as its not needed anymore
        uses: geekyeggo/delete-artifact@v2
        with:
          name: archway
          failOnError: false
        